### ISSUE TITLE
Ошибка при поиске маршрута

### ISSUE THREAD

**Issue by ivashov** [oss-fruct-org/social-navigator#4]
``` java
   java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
            at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
            at java.util.ArrayList.get(ArrayList.java:308)
            at org.fruct.oss.socialnavigator.utils.PointList$1.<init>(PointList.java:143)
            at org.fruct.oss.socialnavigator.utils.PointList.iterator(PointList.java:141)
            at org.fruct.oss.socialnavigator.routing.PathPointList$1.<init>(PathPointList.java:61)
            at org.fruct.oss.socialnavigator.routing.PathPointList.iterator(PathPointList.java:60)
            at org.fruct.oss.socialnavigator.fragments.overlays.RouteOverlayFragment.createOverlay(RouteOverlayFragment.java:221)
            at org.fruct.oss.socialnavigator.fragments.overlays.RouteOverlayFragment.updateOverlays(RouteOverlayFragment.java:243)
            at org.fruct.oss.socialnavigator.fragments.overlays.RouteOverlayFragment.pathsUpdated(RouteOverlayFragment.java:318)
            at org.fruct.oss.socialnavigator.routing.RoutingService$8.run(RoutingService.java:507)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5214)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:814)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:630)
            at dalvik.system.NativeStart.main(Native Method)
```

Возникает периодически

**Comment by ivashov** [comment]
Ошибка возникала при пустом маршруте, исправлено
